version: "3"

services:
  product-feedback-api:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
